# Generated by Django 3.1.5 on 2021-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя* ', max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, help_text='Телефон* ', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Описание', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ФИО отправителя', max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, help_text='Телефон', max_digits=12)),
                ('region_from', models.CharField(help_text='Область отправления', max_length=255)),
                ('region_to', models.CharField(help_text='Область прибытия', max_length=255)),
                ('city_from', models.CharField(help_text='Город отправления', max_length=255)),
                ('city_to', models.CharField(help_text='Город прибытия', max_length=255)),
                ('сargo_from', models.IntegerField(help_text='Масса от, кг')),
                ('сargo_to', models.IntegerField(help_text='Масса до, кг')),
                ('tipe_vehicle', models.CharField(blank=True, help_text='Тип грузовика', max_length=255, null=True)),
                ('value_cargo_from', models.IntegerField(blank=True, help_text='Обьем от, м3', null=True)),
                ('value_cargo_to', models.IntegerField(blank=True, help_text='Обьем до, м3', null=True)),
                ('date', models.DateField(blank=True, help_text='Дата', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
