# Generated by Django 3.1.5 on 2021-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(default=0, help_text='Почта', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='receiver_name',
            field=models.CharField(default=1, help_text='ФИО получателя', max_length=50),
            preserve_default=False,
        ),
    ]
