# Generated by Django 3.1.5 on 2021-02-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210203_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallBack',
        ),
    ]
