# Generated by Django 3.1.5 on 2021-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_delete_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistics_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('skill', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервис-счётчик',
                'verbose_name_plural': 'Сервис-счётчики',
            },
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Плановый заказ', 'verbose_name_plural': 'Плановые заказы'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city_from',
            field=models.CharField(help_text='Город отправления', max_length=255, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city_to',
            field=models.CharField(help_text='Город прибытия', max_length=255, verbose_name='Город прибытия'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateField(blank=True, help_text='Дата', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(help_text='ФИО отправителя', max_length=50, verbose_name='ФИО отправителя'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.DecimalField(decimal_places=0, help_text='Телефон', max_digits=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='receiver_name',
            field=models.CharField(help_text='ФИО получателя', max_length=50, verbose_name='ФИО получателя'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='region_from',
            field=models.CharField(help_text='Область отправления', max_length=255, verbose_name='Область отправления'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='region_to',
            field=models.CharField(help_text='Область прибытия', max_length=255, verbose_name='Область прибытия'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='tipe_vehicle',
            field=models.CharField(blank=True, help_text='Тип грузовика', max_length=255, null=True, verbose_name='Тип грузовика'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='value_cargo_from',
            field=models.IntegerField(blank=True, help_text='Обьем от, м3', null=True, verbose_name='Обьем от, м3'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='value_cargo_to',
            field=models.IntegerField(blank=True, help_text='Обьем до, м3', null=True, verbose_name='Обьем до, м3'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='сargo_from',
            field=models.IntegerField(help_text='Масса от, кг', verbose_name='Масса от, кг'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='сargo_to',
            field=models.IntegerField(help_text='Масса до, кг', verbose_name='Масса до, кг'),
        ),
    ]
