# Generated by Django 3.1.5 on 2021-02-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20210216_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics_info',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='statistics_info',
            name='title',
        ),
        migrations.AddField(
            model_name='statistics_info',
            name='clients',
            field=models.IntegerField(default=1, max_length=255, verbose_name='Довольных клиентов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_info',
            name='reviews',
            field=models.IntegerField(default=2, max_length=255, verbose_name='Отзывы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_info',
            name='vehicle',
            field=models.IntegerField(default=22, max_length=255, verbose_name='Транспортных средств'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_info',
            name='years',
            field=models.IntegerField(default=1, max_length=255, verbose_name='Лет службы'),
            preserve_default=False,
        ),
    ]
