# Generated by Django 3.1.5 on 2021-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20210222_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics_info',
            options={'verbose_name': 'Фейк-счётчик', 'verbose_name_plural': 'Фейк-счётчики'},
        ),
        migrations.AlterField(
            model_name='statistics_info',
            name='clients',
            field=models.PositiveIntegerField(verbose_name='Довольных клиентов'),
        ),
        migrations.AlterField(
            model_name='statistics_info',
            name='reviews',
            field=models.PositiveSmallIntegerField(verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='statistics_info',
            name='vehicle',
            field=models.PositiveSmallIntegerField(verbose_name='Транспортных средств'),
        ),
        migrations.AlterField(
            model_name='statistics_info',
            name='years',
            field=models.PositiveSmallIntegerField(verbose_name='Лет службы'),
        ),
    ]
