# Generated by Django 3.1.5 on 2021-03-02 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20210302_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='dimensions_height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='высота', null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='dimensions_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='длина', null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='dimensions_width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ширина', null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='form_pay',
            field=models.CharField(blank=True, choices=[('Наличные', 'Наличные'), ('Безнал.', 'Безнал.'), ('Комб.', 'Комб.')], help_text='Форма оплаты', max_length=255, null=True, verbose_name='форма оплаты'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='moment_pay',
            field=models.CharField(blank=True, choices=[('На загрузке', 'На загрузке'), ('На выгрузке', 'На выгрузке')], help_text='Момент оплаты', max_length=255, null=True, verbose_name='Момент оплаты'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='notes',
            field=models.CharField(blank=True, help_text='Примечание', max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo_order/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity_vehicles',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Кол-во авто', null=True, verbose_name='Кол-во авто'),
        ),
    ]
